# knitpkg/commands/autocomplete.py

"""
KnitPkg for MetaTrader autocomplete command — generates autocomplete files.

This module handles the generation of MQL include files that provide
autocomplete functionality for KnitPkg-managed packages within MetaEditor.
"""

from typing import Optional
from pathlib import Path
from rich.console import Console

from knitpkg.mql.models import ProjectType, MQLHelixManifest
from knitpkg.core.file_reading import load_helix_manifest
from knitpkg.core.utils import navigate_path
from knitpkg.mql.constants import INCLUDE_DIR

# Import MQL-specific downloader
from knitpkg.mql.dependency_downloader import MQLDependencyDownloader

import typer

# ==============================================================
# AUTOCOMPLETE GENERATOR CLASS
# ==============================================================

class AutocompleteGenerator:
    """Generates autocomplete files for MQL package projects."""

    def __init__(self, console: Console, project_dir: Path):
        """
        Initialize the AutocompleteGenerator.

        Args:
            console: Rich console for output
            project_dir: Root directory of the KnitPkg project
        """
        self.console = console
        self.project_dir = project_dir

    def generate(self) -> None:
        """
        Generate the autocomplete.mqh file.

        This file includes all MQL header files from the project's
        dependencies, making them available for autocompletion
        in MetaEditor.
        """
        manifest: MQLHelixManifest = load_helix_manifest(
            self.project_dir,
            manifest_class=MQLHelixManifest
        )

        if manifest.type != ProjectType.PACKAGE:
            self.console.log(
                "[red]Error:[/] Command `kp-mt autocomplete` only works on projects "
                "with type: package"
            )
            raise SystemExit(1)

        self.console.log(
            f"[bold magenta]autocomplete[/] → generating autocomplete file for " # Alterado
            f"[cyan]{manifest.name}[/]"
        )

        # Resolve dependencies (reuse same logic as install)
        resolved_deps = []
        if manifest.dependencies:
            downloader = MQLDependencyDownloader(self.console, self.project_dir)
            resolved_deps, _dependency_tree = downloader.download_all(
                manifest.dependencies,
                False
            )
        else:
            self.console.log(
                "[yellow]Warning:[/] No dependencies found in manifest. "
                "Autocomplete file will be empty."
            )

        # Generate the file
        autocomplete_dir = self.project_dir / "knitpkg" / "autocomplete"
        autocomplete_dir.mkdir(parents=True, exist_ok=True)
        output_file = autocomplete_dir / "autocomplete.mqh"

        lines = [
            "//+------------------------------------------------------------------+",
            "//|                                          autocomplete.mqh        |",
            "//|              Generated by `kp-mt autocomplete` — DO NOT EDIT     |",
            "//+------------------------------------------------------------------+",
            ""
        ]

        seen_paths = set()
        for _dep_name, dep_path in resolved_deps:
            include_dir = dep_path / INCLUDE_DIR
            if include_dir.exists():
                for mqh in include_dir.rglob("*.mqh"):
                    rel_path = navigate_path(
                        autocomplete_dir,
                        mqh
                    )
                    if str(rel_path) not in seen_paths:
                        lines.append(f'#include "{rel_path.as_posix()}"')
                        seen_paths.add(str(rel_path))

        output_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
        self.console.log(
            f"[bold green]Check[/] Autocomplete file generated → [bold]{output_file}[/]"
        )

# ==============================================================
# CLI REGISTRATION
# ==============================================================

def register(app):
    """Register the autocomplete command with the Typer app."""

    @app.command()
    def autocomplete(
        project_dir: Optional[Path] = typer.Option(
            None,
            "--project-dir",
            "-d",
            help="Project directory (default: current directory)"
        ),
        verbose: Optional[bool] = typer.Option(
            False,
            "--verbose",
            help="Show detailed output"
        )
    ):
        """Generate autocomplete.mqh for MetaEditor for package development."""
        console = Console(log_path=verbose)

        if project_dir is None:
            project_dir = Path.cwd()
        else:
            project_dir = Path(project_dir).resolve()

        generator = AutocompleteGenerator(console, project_dir)
        generator.generate()
