# helix/commands/autocomplete.py
from typing import Optional
from pathlib import Path
from rich.console import Console

from helix.core.models import ProjectType
from helix.core.file_reading import load_helix_manifest
from helix.core.utils import navigate_path
from .install import DependencyDownloader

import typer

# ==============================================================
# AUTOCOMPLETE GENERATOR CLASS
# ==============================================================

class AutocompleteGenerator:
    """Generates autocomplete.mqh file for include projects."""
    
    def __init__(self, console: Console):
        self.console = console
    
    def generate(self) -> None:
        """Generate autocomplete file for the current project."""
        manifest = load_helix_manifest()
        
        if manifest.type != ProjectType.PACKAGE:
            self.console.log("[red]Error:[/] Command `helix autocomplete` only works on projects with type: package")
            raise SystemExit(1)

        self.console.log(f"[bold magenta]helix autocomplete[/] → generating autocomplete file for [cyan]{manifest.name}[/]")

        # Resolve dependências (reusa a mesma lógica do install)
        resolved_deps = []
        if manifest.dependencies:
            downloader = DependencyDownloader(self.console)
            resolved_deps, _dependency_tree = downloader.download_all(manifest.dependencies, False)
        else:
            self.console.log("[yellow]Warning:[/] No dependencies found in manifest. Autocomplete file will be empty.")

        # Gera o arquivo
        autocomplete_dir = Path("helix/autocomplete")
        autocomplete_dir.mkdir(parents=True, exist_ok=True)
        output_file = autocomplete_dir / "autocomplete.mqh"

        lines = [
            "//+------------------------------------------------------------------+",
            "//|                                          autocomplete.mqh        |",
            "//|              Generated by `helix autocomplete` — DO NOT EDIT     |",
            "//+------------------------------------------------------------------+",
            ""
        ]

        seen_paths = set()
        for _dep_name, dep_path in resolved_deps:
            include_dir = dep_path / "helix" / "include"
            if include_dir.exists():
                for mqh in include_dir.rglob("*.mqh"):
                    rel_path = navigate_path(Path.cwd() / "helix" / "autocomplete", mqh)
                    if str(rel_path) not in seen_paths:
                        lines.append(f'#include "{rel_path.as_posix()}"')
                        seen_paths.add(str(rel_path))

        output_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
        self.console.log(f"[bold green]Check[/] Autocomplete file generated → [bold]{output_file}[/]")

# ==============================================================
# CLI REGISTRATION
# ==============================================================

def register(app):
    @app.command()
    def autocomplete(verbose: Optional[bool] = typer.Option(False, "--verbose", "-v", help="Show detailed output with file/line information")):
        """Prepare include: create autocomplete.mqh to aid the includes development."""

        console = Console(log_path=verbose)
        generator = AutocompleteGenerator(console)
        generator.generate()    